### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by shahabmusic** [wildan2711/mqtt-android-tutorial#1]
Hi I tried everything but I still get the above error. Do you think what it could be?

here is my stack dump onFaliure()

06-04 21:00:03.416 6931-6931/? W/System.err: java.lang.Throwable: stack dump
06-04 21:00:03.426 6931-6931/? W/System.err:     at java.lang.Thread.dumpStack(Thread.java:489)
06-04 21:00:03.426 6931-6931/? W/System.err:     at helpers.MqttHelper$2.onFailure(MqttHelper.java:85)
06-04 21:00:03.426 6931-6931/? W/System.err:     at org.eclipse.paho.android.service.MqttTokenAndroid.notifyFailure(MqttTokenAndroid.java:146)
06-04 21:00:03.426 6931-6931/? W/System.err:     at org.eclipse.paho.android.service.MqttAndroidClient.simpleAction(MqttAndroidClient.java:1501)
06-04 21:00:03.426 6931-6931/? W/System.err:     at org.eclipse.paho.android.service.MqttAndroidClient.connectAction(MqttAndroidClient.java:1439)
06-04 21:00:03.426 6931-6931/? W/System.err:     at org.eclipse.paho.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.java:1368)
06-04 21:00:03.426 6931-6931/? W/System.err:     at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
06-04 21:00:03.426 6931-6931/? W/System.err:     at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
06-04 21:00:03.426 6931-6931/? W/System.err:     at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
06-04 21:00:03.426 6931-6931/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-04 21:00:03.426 6931-6931/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
06-04 21:00:03.426 6931-6931/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5017)
06-04 21:00:03.426 6931-6931/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
06-04 21:00:03.426 6931-6931/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
06-04 21:00:03.426 6931-6931/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
06-04 21:00:03.426 6931-6931/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
06-04 21:00:03.426 6931-6931/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
06-04 21:00:03.426 6931-6931/? W/Mqtt: Failed to connect to: server java.lang.NullPointerException

**Comment by wildan2711** [comment]
Have you set the broker URI in the MqttHelper.java class?

https://github.com/wildan2711/mqtt-android-tutorial/blob/master/app/src/main/java/helpers/MqttHelper.java

If you followed my tutorial, I have given instructions on how to set up a private cloud broker, which would need you to sign up. Otherwise you could use a local broker using mosquitto or there is a public broker available at HiveMQ: http://www.hivemq.com/try-out/

**Comment by wildan2711** [comment]
Ok, I have modified my code to use HiveMQ as the broker, it should work now. https://github.com/wildan2711/mqtt-android-tutorial/commit/8e77590fd612e9123ad6624c90b044bdffed8b5f

**Comment by shahabmusic** [comment]
Thank you. All working fine now.

**Comment by wildan2711** [comment]
Cool. If you found this useful, give this repository a star. Means a lot, thank you
